server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.php index.html;

    location = / {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
    }

    location = /index {
        return 301 /;
    }

    location = /orcamento {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/orcamento.php;
        fastcgi_param SCRIPT_NAME /orcamento.php;
    }

    location = /criacao-de-sites-profissionais {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/criacao-de-sites-profissionais.php;
        fastcgi_param SCRIPT_NAME /criacao-de-sites-profissionais.php;
    }

    location = /templates-elementor-wordpress-figma {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/templates-elementor-wordpress-figma.php;
        fastcgi_param SCRIPT_NAME /templates-elementor-wordpress-figma.php;
    }

    location = /portfolio-sites-profissionais {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/portfolio-sites-profissionais.php;
        fastcgi_param SCRIPT_NAME /portfolio-sites-profissionais.php;
    }

    location = /sobre-daiane-ferreira-web-designer {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/sobre-daiane-ferreira-web-designer.php;
        fastcgi_param SCRIPT_NAME /sobre-daiane-ferreira-web-designer.php;
    }

    location = /contato-criacao-de-sites {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/contato-criacao-de-sites.php;
        fastcgi_param SCRIPT_NAME /contato-criacao-de-sites.php;
    }

    location = /orcamento.php {
        return 301 /orcamento;
    }

    location = /criacao-de-sites-profissionais.php {
        return 301 /criacao-de-sites-profissionais;
    }

    location = /templates-elementor-wordpress-figma.php {
        return 301 /templates-elementor-wordpress-figma;
    }

    location = /portfolio-sites-profissionais.php {
        return 301 /portfolio-sites-profissionais;
    }

    location = /sobre-daiane-ferreira-web-designer.php {
        return 301 /sobre-daiane-ferreira-web-designer;
    }

    location = /contato-criacao-de-sites.php {
        return 301 /contato-criacao-de-sites;
    }

    location = /index.php {
        return 301 /;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}